# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-20 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.CharField(blank=True, choices=[('公告', '公告'), ('管理', '管理')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.CharField(max_length=800),
        ),
    ]
