# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-22 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tadmin', '0004_auto_20171021_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='best_commnet',
            field=models.BooleanField(default=False),
        ),
    ]
